#################################################################################################
# 修改 TNAME: NEWIFI3 中的NEWIFI3为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
#################################################################################################
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        #cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' configs/templates/$TNAME.config
        ###################################################################################################
        # 因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ###################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' configs/templates/$TNAME.config      #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' configs/templates/$TNAME.config          #删除配置项DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' configs/templates/$TNAME.config       #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' configs/templates/$TNAME.config         #删除配置项MINIEAP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' configs/templates/$TNAME.config     #删除配置项NJIT_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' configs/templates/$TNAME.config            #删除配置项FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' configs/templates/$TNAME.config            #删除配置项FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' configs/templates/$TNAME.config      #删除配置项SOFTETHERVPN_SERVER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' configs/templates/$TNAME.config      #删除配置项SOFTETHERVPN_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' configs/templates/$TNAME.config         #删除配置项SOFTETHERVPN_CMD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' configs/templates/$TNAME.config                  #删除配置项TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' configs/templates/$TNAME.config      #删除配置项TRANSMISSION_WEB_CONTROL
        ####################################################################
        # 以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件。
        ####################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> configs/templates/$TNAME.config       #删除DOGCOM
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> configs/templates/$TNAME.config    #删除MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> configs/templates/$TNAME.config      #删除MINIEAP
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> configs/templates/$TNAME.config  #删除NJIT_CLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> configs/templates/$TNAME.config         #添加FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=y" >> configs/templates/$TNAME.config         #添加FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> configs/templates/$TNAME.config   #删除SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> configs/templates/$TNAME.config  #删除SOFTETHERVPN_SERVER
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> configs/templates/$TNAME.config  #删除SOFTETHERVPN_CLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> configs/templates/$TNAME.config     #删除SOFTETHERVPN_CMD
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=y" >> configs/templates/$TNAME.config              #添加TRANSMISSION
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=y" >> configs/templates/$TNAME.config  #添加TRANSMISSION_WEB_CONTROL
        #########################################################################################
        # 自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        # 格式如下：
        # sed -i '/自定义项/d' .config
        # echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo fakeroot ./build_firmware_modify $TNAME
        #sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
